# Generated by Django 4.2.9 on 2024-05-26 10:42

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст конента'),
        ),
    ]
