# Generated by Django 4.2.9 on 2024-05-26 13:03

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='video',
        ),
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, default='content-default.jpg', null=True, upload_to='uploads/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст конента'),
        ),
    ]
