# Generated by Django 4.2.9 on 2024-05-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post-default.jpg', null=True, upload_to='uploads/'),
        ),
    ]
