# Generated by Django 4.2.9 on 2024-05-28 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='userpic.png', null=True, upload_to=user.models.user_directory_path, verbose_name='Фото')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1, null=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('tg_chat', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='ИД ТГ чата')),
                ('tg_token', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='ИД ТГ чата')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='user.role', verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
