# Generated by Django 4.2.9 on 2024-05-26 23:22

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='userpic.png', null=True, upload_to=user.models.user_directory_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tg_chat',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='ИД ТГ чата'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tg_token',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='ИД ТГ чата'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1, null=True),
        ),
    ]
