# Generated by Django 4.2.9 on 2024-05-26 23:23

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_age_remove_profile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='img/userpic.png', null=True, upload_to=user.models.user_directory_path, verbose_name='Фото'),
        ),
    ]
