# Generated by Django 4.2.9 on 2024-05-26 23:24

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='userpic.png', null=True, upload_to=user.models.user_directory_path, verbose_name='Фото'),
        ),
    ]
